### ISSUE TITLE
Downsampling interface for Epoch objects

### ISSUE THREAD

**Issue by Antzyx** [3dgeo-heidelberg/py4dgeo#347]
Hello. Thank you very much for your work on this package.

I tried to perform what I assume to be a common operation : I wanted to run icp_with_stable_areas on a point cloud and ran out of memory, so I wanted to downsample my epoch. Here is what I had to do :

```
indices = np.random.choice(epoch.cloud.shape[0], int(epoch.cloud.shape[0] / factor), replace=False)
 xyz = epoch.cloud[indices]
 xyz = "\n".join([" ".join(map(str, point)) for point in xyz])
 try:
     with open("temp.txt", "w", encoding='utf8') as f:
         f.write(xyz)
     new_epoch = py4dgeo.read_from_xyz("temp.txt")
 except Exception as e:
      if os.path.exists("temp.txt"):
          os.remove("temp.txt")
      raise e
```

I am not sure if I missed some feature which would have allowed me to do this faster, but this looks like an overly complicated way of downsampling an Epoch. I tried simply `epoch.cloud = epoch.cloud[indices]` but this creates a segmentation error. Here are some suggestions to support this at different levels :
- adding a downsampling method for Epoch
- adding an Epoch constructor from x/y/z python objects instead of only system files (if this already exists, expose it more clearly in the doc)
- support epoch.cloud = ...

Keep up the good work and thank you again !

**Comment by dokempf** [comment]
Hey, thanks for reporting this! This should be absolutely something easily done within `py4dgeo` and I will bring it up at the next developer meeting. Here is my analysis of what happens:

* Although `epoch.cloud = ...` does not throw an error, it leaves the `Epoch` object in an unusable state, as we require point clouds to be continuous in memory. The checks regarding that are in `__init__`, rather than a setter for `.epoch`, that is why you do not run through that code path. This should be fixed.
* That being said there is a way of doing what you want in `downsampled = py4dgeo.Epoch(epoch.cloud[indices])`
* However, this is also not desirable because as you have to (manually) downsample all other data like normals and additional dimensions as well.

To conclude, I think two things should be done:
* indeed a `downsample` method would be a good solution, that handles the downsampling of all relevant data
* `.cloud` and friends should be properties that cannot be set to prevent the errors you ran into.

**Comment by dokempf** [comment]
@Antzyx This can now (on `main`) also be achieved as `epoch[indices]` which returns exactly what `py4dgeo.Epoch(epoch.cloud[indices])` did, but also normals and additional dimensions are handled correctly.
